language: python
os:
- linux
cache: pip
python:
- 3.6
install:
- pip install -r requirements.txt
- pip install -e .[test]
script:
- pytest
deploy:
  provider: pypi
  user: smomni
  password:
    secure: 8n3lxT91WJWvW36bZuYlh4RdP/asyQk8UR8LzENZDPMdQnoMeFx6+a9UmOuIGRCJGlTH0bK7J6VJ2X6eXgfVTAFgpSEzH31zGkESycui32SMg2EPhCHTCCbSz1U0qcNHCVIQvUuwmjc3oYyOvazIa6mSZlguIlD+RNoBq+M9sMjYexnzUcsIwa2QRiXWrsJMmXGS7nZPt0HppPXgR4pfNRRo7zCv2TSQiwPIly8PvkSNzCMhbeqmRD7NXba8b0bL/eVoNkhZqkPDOZU/OPSFJbecOny7pLsgAEs70e76LQdLZaJEl1Fqx1lWTDOGXgYnuA3q+f6Y/wrY97X5PRJU0EpA2O7IwX/tjcFsvw81ChT/uMlESGA3gD2tYI4uXEjQKX2CFxdSFy1WJFloxqPmXAQI2T9xj3sEzSiqEq0bjcfP9YM4QKH7fFEGMga3pmWa3ZZhtuC5tSen4wg3aAfijFhDyDc+jE5WjAUyrDaKXKy80k8B32Ad1j9JDWfYatcTTVQMcOXOAT7xEYKHe9OdzkwihkYnhw7iBqQ6pGAT71DowBcdSE+5+snj2fAgl+PoFNGPlk2yyZcuTHjxWkMsyKjO0QejMpWhEkXp5fai5XgoqLmkQLfJSlVxgN+hQbUgNwnfZ/z5YHEgtbOzSPYf5C3Fp51kvVW1Ydf9JxbIn74=
  on:
    tags: true
